language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - android-29
    - build-tools-28.0.3

branches:
  only:
    - master
    - dev

git:
  depth: 3


before_install:
  - gradle -b wrapper.gradle


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache


after_success:
  - bash <(curl -s https://codecov.io/bash)
